name: Tests
on: [push, pull_request]
jobs:
  # Code Syntax Check
  syntax:
    strategy:
      fail-fast: false
    runs-on: [self-hosted, docker]
    name: Flake8 Syntax Check
    container:
      image: python:3.9.5
      options: --user 0:0
      volumes:
        - /home/buildbot/.ssh:/root/.ssh
    steps:
      - name: Install SSH client
        run: apt update && apt -y install openssh-client
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Create flake file
        run: echo "" >> .flake8
      - name: Check python syntax
        uses: cclauss/Find-Python-syntax-errors-action@master
  # Code Format Check
  black:
    name: Black
    runs-on: [self-hosted, docker]
    container:
      image: kiwicom/black
      options: --user 0:0
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Run Black Check
        run: black . --check
